portal:
  server:
    graphqlServer:
      genericEnv:
        CHAOS_CENTER_UI_ENDPOINT: http://litmuschaos-frontend-service.litmuschaos.svc.cluster.local:9091
  frontend:
    service:
      type: NodePort

mongodb:
  enabled: true
  global:
    defaultStorageClass: "gp2"
    security:
      allowInsecureImages: "true"
  image:
    registry: ghcr.io/zcube
    repository: bitnami-compat/mongodb
    tag: 6.0.5
  metrics:
    enabled: true
  volumePermissions:
    enabled: true
    image:
      registry: docker.io
      repository: bitnamilegacy/os-shell
      tag: 12-debian-12-r51
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "gp2"
  replicaCount: 1
  metrics:
    enabled: false
    repository: bitnami/mongodb-exporter
    tag: latest
  auth:
    enabled: true
    rootPassword: litmus
    username: litmus
    password: litmus
    database: litmus