apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: joyful-service-chaos-engine
  namespace: joyful-service-canary
spec:
  engineState: active                 # set to 'stop' to pause via Git and 'active' to run
  annotationCheck: 'true'             # require app annotation as extra guard
  jobCleanUpPolicy: delete            # retain or delete
  appinfo:
    appns: joyful-service-canary
    applabel: app=joyful-canary
    appkind: rollout
  chaosServiceAccount: joyful-litmus-admin
  experiments:
    # - name: pod-delete
    #   spec:
    #     components:
    #       env:
    #         - name: TARGET_PODS
    #           value: ''             # leave empty to select via label
    #         - name: PODS_AFFECTED_PERC
    #           value: ''
    #         - name: TOTAL_CHAOS_DURATION
    #           value: '60'
    #         - name: CHAOS_INTERVAL
    #           value: '10'
    #         - name: FORCE
    #           value: 'false'
    #       resources: {}	
    #       statusCheckTimeouts: {}
    #     # Add steady-state probes (HTTP/Prometheus) to gate success/failure
    #     probe:
    #       - name: joyful-liveness
    #         type: "httpProbe"
    #         mode: "Edge"               # The probe will check hypothesis both before and after the Test.
    #         runProperties:
    #           probeTimeout: 5s
    #           retry: 2
    #           interval: 5s
    #           initialDelay: 1s
    #           attempt: 3
    #           stopOnFailure: true
    #         httpProbe/inputs:
    #           url: "http://joyful-canary.joyful-service-canary.svc.cluster.local:5000/ping"
    #           insecureSkipVerify: false
    #           method: 
    #             get:
    #               criteria: "=="
    #               responseCode: "200"
    - name: pod-memory-hog
      spec:
        components:
          env:
            - name: TARGET_PODS
              value: ''             # leave empty to select via label
            - name: PODS_AFFECTED_PERC
              value: ''
            - name: TOTAL_CHAOS_DURATION
              value: '60'
            - name: NUMBER_OF_WORKERS
              value: '4'
            - name: MEMORY_CONSUMPTION # memory consumption value in MB
              value: '500'
            - name: CHAOS_INTERVAL
              value: '10'
            - name: FORCE
              value: 'false'
          resources: {}	
          statusCheckTimeouts: {}
        # Add steady-state probes (HTTP/Prometheus) to gate success/failure
        probe:
          - name: joyful-liveness
            type: "httpProbe"
            mode: "Edge"               # The probe will check hypothesis both before and after the Test.
            runProperties:
              probeTimeout: 5s
              retry: 2
              interval: 5s
              initialDelay: 1s
              attempt: 3
              stopOnFailure: true
            httpProbe/inputs:
              url: "http://joyful-canary.joyful-service-canary.svc.cluster.local:5000/ping"
              insecureSkipVerify: false
              method: 
                get:
                  criteria: "=="
                  responseCode: "200"