apiVersion: v1
kind: ServiceAccount
metadata:
  name: joyful-litmus-admin
  namespace: joyful-service-canary
  labels:
    name: joyful-litmus-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: joyful-litmus-admin-role
  namespace: joyful-service-canary
rules:
# read access to list/watch pods, deployments, jobs, replicasets, chaos resources
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""
      - "apps"
      - "batch"
      - "litmuschaos.io"
    resources:
      - secrets
      - deployments
      - jobs
      - pods
      - pods/log
      - rollouts
      - events
      - configmaps
      - chaosengines
      - chaosexperiments
      - chaosresults
      - replicasets
# full access to create/update/delete chaos resources
  - verbs:
      - get
      - create
      - update
      - patch
      - list
      - watch
      - delete
    apiGroups:
      - ""
      - "apps"
      - "batch"
      - "litmuschaos.io"
    resources:
      - pods
      - events
      - jobs
      - chaosresults
      - chaosengines


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: joyful-litmus-admin-role-binding
  namespace: joyful-service-canary
  labels:
    name: joyful-litmus-admin-role-binding
subjects:
  - kind: ServiceAccount
    name: joyful-litmus-admin
    namespace: joyful-service-canary
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: joyful-litmus-admin-role
