# Remove all permissions from the default project so that no one can deploy to the default project.
# This is a security measure to prevent accidental deployments to the default project.
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  sourceRepos: []
  sourceNamespaces: []
  destinations: []
  namespaceResourceBlacklist:
  - group: '*'
    kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  name: cloudnova
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Cloudnova Applications project
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/sysadmin-exe/argocd-rollout-lab'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  name: cloudnova-litmuschaos
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: cloudnova-litmuschaos Applications project
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/sysadmin-exe/argocd-rollout-lab'
  orphanedResources:
    warn: false
    ignore:
      - group: ""           # Pods created by the runner
        kind: Pod
      - group: batch        # Jobs created by experiments
        kind: Job
      - group: litmuschaos.io
        kind: ChaosResult   # Results CR created by Litmus

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sre-tools
  namespace: argocd
spec:
  description: SRE tools (OpenTelemetry, LitmusChaos) managed by Argo CD
  sourceRepos:
    - https://github.com/sysadmin-exe/argocd-rollout-lab
    - https://open-telemetry.github.io/opentelemetry-helm-charts
    - https://litmuschaos.github.io/litmus-helm
  destinations:
    - namespace: otel-demo
      server: https://kubernetes.default.svc
    - namespace: litmuschaos
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true